service: myawsreactnodeserverlessproject

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs12.x
  profile: aws-react-node-serverless-backend-user
  region: us-east-1
  environment:
    tableName: dssUserTable
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "lambda:*"
          Resource: "*"

        - Effect: "Allow"
          Action:
            - "dynamodb:*"
          Resource: "*"

plugins:
  - serverless-offline

custom:
  tableName: dssUserTable

functions:
  auth:
    handler: lambdas/endpoints/auth.Register
    events:
      - http:
          path: /user/signup
          method: post
  signinUser:
    handler: lambdas/endpoints/signinUser.signin
    events:
      - http:
          path: /user/signin
          method: post
          cors: true
  category:
    handler: lambdas/endpoints/category.addCategory
    events:
      - http: 
          path: /addcategory
          method: post
  getCategory:
    handler: lambdas/endpoints/category.getCategory
    events:
      - http:
          path: /getcategory/{id}
          method: get
  updateCategory:
    handler: lambdas/endpoints/category.updateCategory
    events: 
      - http: 
          path: /updatecategory/{id}
          method: patch
  getAllCategory:
    handler: lambdas/endpoints/category.getAllCategory
    events:
      - http:
          path: /getallcategory
          method: get
          cors: true
  addTopic:
    handler: lambdas/endpoints/topic.addTopic
    events:
      - http:
          path: /addtopic
          method: post
          cors: true
  getAllTopic:
    handler: lambdas/endpoints/topic.getAllTopic
    events:
      - http:
          path: /getalltopics
          method: get
          cors: true
  getSingleTopic:
    handler: lambdas/endpoints/topic.getSingleTopic
    events:
      - http:
          path: /getsingletopic/{id}
          method: get
          cors: true
  updateTopic:
    handler: lambdas/endpoints/topic.updateTopic
    events:
      -  http:
          path: /update/topic/{id}
          method: patch
          cors: true

resources:
  Resources:
    UserDynamoDbTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: dssUserTable
        AttributeDefinitions:
          - AttributeName: email
            AttributeType: S
        KeySchema:
          - AttributeName: email
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
    CategoryDynamoDbTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: CategoryTable
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
    TopicDynamoTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: TopicTable
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5